### ISSUE TITLE
Update visit page

### ISSUE THREAD

**Issue by skyheat** [codersforcauses/poops#111]
## Basic Information

Updating the visit page with new specifications

- [x] Add day names (monday etc.)
- [x] Hide reporting to edit (report an incident, register vet concern). Buttons should only show up when clicking edit
- [x] Display name should be called client name
- [x] End time not necessary, all we need is duration. Create a drop down with times in increments of 15. (15mins, 30mins, 45mins, ..., 2 hours etc.)
- [x] client/pet name should be pulled from contact list, similar to home page form. Drop down with the names but can also search.

## Other Information

Potential scopes:

**Comment by Techno-UWA** [comment]
Hey @skyheat, is the last thing to do for 'Update visit page' the hiding of the report buttons?

If so is the task asking for the buttons to only be visible when editing the visit instance OR to only be visible in read only mode (when not editing)?

Visible in Read mode?
![image](https://user-images.githubusercontent.com/117506201/206608709-749bdb03-5d49-4515-9291-4c228ac90810.png)


Or visible in edit mode?

![image](https://user-images.githubusercontent.com/117506201/206608158-a628d0cf-b7ea-4e5d-80aa-577a629bb69a.png)

**Comment by dct0** [comment]
@Techno-UWA This issue is resolved in the #119 PR
