### ISSUE TITLE
Design a stats page for admins

### ISSUE THREAD

**Issue by NicholasChoong** [codersforcauses/poops#135]
**Is your feature request related to a problem? Please describe.**
Poops need stats for funding.

**Describe the solution you'd like**
Use figma to design a page for admins that contains:
- Per volunteer:
  - Total # visits, minutes, kms over the period
  - Average number of visits, minutes, kms per week 
  - Average number of clients

This page should be made for desktop view.

**Comment by scratchclaggy** [comment]
@NicholasChoong @skyheat What does avg number of clients mean?

**Comment by NicholasChoong** [comment]
You average out the number of clients across the volunteers so in the end, you will get the average number of clients per volunteer.

**Comment by NicholasChoong** [comment]
UPDATE: This page should be made for desktop view.

**Comment by Techno-UWA** [comment]
Hey @NicholasChoong, are the totals overall totals? Like the total/collective number of visits from all volunteers or are the totals still per volunteer?

**Comment by Techno-UWA** [comment]
Hey @NicholasChoong, just clarifying some more details about the Admin profile view.
 
1.	 Does the Admin login with the same sign in page as everyone else and then get directed to an Admin PC version of the site or is there a separate login page for Admin built for PC? 
2.	Also will the Admin account be a normal account with some extra features or will the Admin have a completely separate version of the website (built for PC?)
3.	Also should we keep a bottom NavBar like in the phone version or do you think we should use a drop down or slide out menu panel for the Admin PC version?
4.	Also has any other Admin functionality or pages been designed and built yet? 
5.	If not would you like me to make a separate folder in pages and components for Admin or would you like it to be integrated into the normal pages and components?

**Comment by Techno-UWA** [comment]
I guess the big question is if any Admin stuff has been designed or built yet or if we get to design and build it from scratch?

**Comment by skyheat** [comment]
Should be desktop view, design is not important. Aim for functionality.
