### ISSUE TITLE
Refactor Navbar UI

### ISSUE THREAD

**Issue by skyheat** [codersforcauses/poops#150]
**Is your feature request related to a problem? Please describe.**
The current navbar could better conform to industry standards.

**Describe the solution you'd like**
An instagram style navbar. All icons should be outline but filled when on the page. 

![239D1CDF-6761-484D-AC73-0E8252830DDC](https://user-images.githubusercontent.com/6574274/207625680-44a8981e-4fea-4608-ad84-579908a1d914.jpg)

![image](https://user-images.githubusercontent.com/6574274/207626303-9da77b52-9894-4d10-a9ca-466f1925e8bd.png)
Note: This is just a scrappy design I threw together for the sake of visualisation and can be changed. Just get approval from me.

The svg file for the poops dog icon can be found in `../public/images/poops.svg`

**Comment by Techno-UWA** [comment]
## Observations
Hey @skyheat, it looks like there's been a bit of work on #150  Refactor the Navbar UI already though I think there are some areas of improvement. I think in particular if we're going to use the same Navbar for PC layout it may need some adjustments to adapt to the different screen size. 

## Questions
But I was wondering if there was anything in particular that still needs to be done? Or is the goal of the issue to make the Navbar even more similar to the Instagram Navbar?

#### (Image is from the website as it is at the moment, I think?)
![image](https://user-images.githubusercontent.com/117506201/212805280-e8deac13-2586-46f7-a91d-020da551b250.png)

**Comment by skyheat** [comment]
Work has been previously done on it but feel free to scrap it entirely if you wish :)

The goal is for the UI to be similar to an instagram navbar rather than the current one, in essence, just removing the middle dog visits icon and making it an icon in the same vein as the others.
