### ISSUE TITLE
Validate data retrieved from Firestore

### ISSUE THREAD

**Issue by NicholasChoong** [codersforcauses/poops#159]
**Is your feature request related to a problem? Please describe.**
The current code only cast type to the retrieved data.

**Describe the solution you'd like**
Use `Zod` to validate the data.

We are in the process of changing our database schema so this issue is blocked by #155 .

**Comment by scratchclaggy** [comment]
Is validating data from reads necessary if we're also doing validation on writes?

**Comment by NicholasChoong** [comment]
I personally prefer to check data retrieved from an external source as we have no idea what sort of changes have been made to data outside of the app. Also, Firestore security rules only apply to the request coming from the client side apps so Firebase admin SDK or Functions can bypass these rules.
You have a point though as the only part that is vulnerable to change is on the client side only.

**Comment by skyheat** [comment]
Also @JeremiahPinto roasted us.
