### ISSUE TITLE
Display user name in the Welcome message

### ISSUE THREAD

**Issue by NicholasChoong** [codersforcauses/poops#160]
**Is your feature request related to a problem? Please describe.**
The welcome message in the home page does not display the name of the user.

**Describe the solution you'd like**
Display the user name if the user is authenticated

**Comment by scratchclaggy** [comment]
I've already covered this while working on #155 sorry.

**Comment by justinliangg** [comment]
I have also already done this while working on #142

**Comment by NicholasChoong** [comment]
Alright, I'll close this issue.
