### ISSUE TITLE
BUG: `Contact` page crashes for new users

### ISSUE THREAD

**Issue by NicholasChoong** [codersforcauses/poops#168]
**Is your feature request related to a problem? Please describe.**
Contact name is undefined and crashes the contact page when a newly created user attempts to go to that page.

**Comment by skyheat** [comment]
Crashes for users who use the old schema. Delete your user in the firestore if you are running into issues. Should be fine when we nuke the firestore.

**Comment by NicholasChoong** [comment]
Nuked firestore but the error still persist.

**Comment by skyheat** [comment]
Issue has been fixed. It was a Nicholas Choong Wei Chun skill issue.
