### ISSUE TITLE
PWA layout error on initial load

### ISSUE THREAD

**Issue by skyheat** [codersforcauses/poops#172]
**Is your feature request related to a problem? Please describe.**
The navbar is further above the bottom of the screen when a user initially logs into to the app for the first time. Fixed on app refresh.

<img src="https://user-images.githubusercontent.com/6574274/210834983-d2e1a65f-d59c-4429-a8b0-7470e11b44a2.png" width="200" height="400" />

**Describe the solution you'd like**
The navbar layout should not be broken upon initial login.

**Comment by pavo-etc** [comment]
Unable to reproduce on Android 13, on Chrome and Firefox

**Comment by skyheat** [comment]
This might be helpful

https://discussions.apple.com/thread/251535534
