### ISSUE TITLE
Link phone login to backend

### ISSUE THREAD

**Issue by skyheat** [codersforcauses/poops#184]
**Is your feature request related to a problem? Please describe.**
Currently the issue #92 covers the frontend of the phone login. 

**Describe the solution you'd like**
Link the backend to the phone login, prompting for a [OTP ](https://firebase.google.com/docs/auth/web/phone-auth) linking to filling out account information if it's new (#93) but redirecting straight to index if is an existing user.

**Comment by justinliangg** [comment]
https://github.com/firebase/firebaseui-web
