### ISSUE TITLE
Create custom hooks to retrieve documents using `react-query`

### ISSUE THREAD

**Issue by NicholasChoong** [codersforcauses/poops#193]
**Is your feature request related to a problem? Please describe.**
We need to cache documents retrieved from the `incidents` and `vet_concerns` collections.

**Describe the solution you'd like**
Create 2 custom hooks called `useIncident` and `useVetConcern`.
The hooks should contain a query function that retrieves the documents from the collection and a mutation function that updates the documents.

**Comment by Techno-UWA** [comment]
Hey @NicholasChoong, it seems like this issue might be linked to another pull request? Can it be closed?

**Comment by Techno-UWA** [comment]
Issue completed through other merged pull requests
