### ISSUE TITLE
Saving fields creates a new contact

### ISSUE THREAD

**Issue by skyheat** [codersforcauses/poops#197]
**Is your feature request related to a problem? Please describe.**
Currently, editing your profile and saving it creates a new contact rather than updating your profile.

**Describe the solution you'd like**
Saving the edited fields should just update the profile.

**Comment by scratchclaggy** [comment]
Can we confirm that this is still a bug? I believe this was fixed with [this commit](https://github.com/codersforcauses/poops/commit/a87f77a76bbeaf4afbc7a4feb4edad109e719323).

**Comment by skyheat** [comment]
Interesting. The bug is no longer happening for me but was at the workshop yesterday. Can others confirm this? @jordantgiang
