### ISSUE TITLE
Buttons disappear when notes are too long

### ISSUE THREAD

**Issue by skyheat** [codersforcauses/poops#198]
**Is your feature request related to a problem? Please describe.**
Unable to see the edit, vet concern and incident buttons when notes is too long

**Describe the solution you'd like**
Buttons shouldn't disappear. 

**Describe alternatives you've considered**

**Additional context**

**Comment by justinliangg** [comment]
![image](https://user-images.githubusercontent.com/94982557/212466829-3b6baf4b-d918-4315-8f78-1ac1056fb0db.png)
