### ISSUE TITLE
Centralise Visits

### ISSUE THREAD

**Issue by skyheat** [codersforcauses/poops#208]
**Is your feature request related to a problem? Please describe.**
Currently, visits are not centralise but are unique to each user. This is an issue as it makes querying the data troublesome.

**Describe the solution you'd like**
Centralise the data.

**Comment by NicholasChoong** [comment]
Just found out that there is a function to query all documents under a subcollection. The function is called `collectionGroup`. We dont need this anymore.
https://firebase.blog/posts/2019/06/understanding-collection-group-queries
