### ISSUE TITLE
Stats Page Updates

### ISSUE THREAD

**Issue by skyheat** [codersforcauses/poops#209]
**Is your feature request related to a problem? Please describe.**
Currently, the stats page only contains totals. As POOPS needs the statistics for grants, it would be useful to be able to query specific information. 

**Describe the solution you'd like**
Essentially:
- Averages more important than total (Have totals be ‘tooltips’ or something similar)
- Per week breakdown
- Date range picker (high priority), Default range should be the current financial year

This issue will be **blocked** until issue #208 is completed as centralising visits will make querying easier

**Comment by justinliangg** [comment]
https://firebase.blog/posts/2019/06/understanding-collection-group-queries

**Comment by justinliangg** [comment]
https://medium.com/doctolib/react-query-cachetime-vs-staletime-ec74defc483e
