### ISSUE TITLE
Reporting an incident for a visit doesn't work

### ISSUE THREAD

**Issue by jordantgiang** [codersforcauses/poops#216]
## Basic Information
When submitting the Report Incident Form, the incident is not being added to the notes like "Register Vet Concern" is.

## Describe the solution you'd like
Fix bug

The relevant information of the Report Incident Form is to be appended to the end of the notes.

**Comment by RadioArsenic** [comment]
The vet concerns and incidents forms also look different in the way that they prefill values, so I'll try and fix that too
