### ISSUE TITLE
Change favicon to POOPS branding

### ISSUE THREAD

**Issue by skyheat** [codersforcauses/poops#22]
## Basic Information
- [ ] Change favicon to POOPS branding

POOPS branding can be found [here](https://www.dropbox.com/scl/fo/qlr56x6olkfeez9wvo9o3/h?dl=0&rlkey=yzkiez1go0j31zk91ct1htjgi)

you can generate your own from [here](https://www.favicon-generator.org/) then replace the whole /public/favicon folder

## Other Information
Potential scopes:

**Comment by NicholasChoong** [comment]
you can generate your own from [here](https://www.favicon-generator.org/) then replace the whole /public/favicon folder
