### ISSUE TITLE
Move `sendEmail` Next API to the frontend

### ISSUE THREAD

**Issue by NicholasChoong** [codersforcauses/poops#230]
**Is your feature request related to a problem? Please describe.**
The current function is implemented in Next API. The function might be redundant as the function can be done on the frontend.

**Describe the solution you'd like**
Instead of using the Next API to create a `mail` document, create the `mail` docs right after the user has submitted the `vet` or `incident` form on the frontend.

Just this one line of code:
```ts
// src/pages/api/sendEmail.ts
await firestore.collection('mail').add(email)
```
Keep in mind that the above code is an API from the `firebase-admin` and it is basically just `firebase` version 8 that is using classes. Convert it to use APIs from `firebase` version 9 which uses functions.

**Comment by Techno-UWA** [comment]
Hey @pavo-etc, @NicholasChoong, I've managed to get the emails functioning in the emulator with a testing email but I'm having some trouble getting it to work with the environmental variables (I'm currently just putting the email where it should be calling the env)

I'm also not entirely sure how to translate it to the production version with the other email and different setup for the emails extension.

I've pushed everything so far to the branch but you may need to use a different email.
