### ISSUE TITLE
Create sign up, sign in and forget password forms

### ISSUE THREAD

**Issue by NicholasChoong** [codersforcauses/poops#25]
## Basic Information
- [x] Create a component for the forms.
- [ ] Allow backend to access form components.
- [x] Use a library that has all the login icons from different platforms.

Example: https://github.com/jarrodwatts/pineapple/blob/main/components/Auth.tsx

## Other Information
Potential scopes: Native login.

**Comment by scratchclaggy** [comment]
Completed / irrelevant
