### ISSUE TITLE
Link roles to backend

### ISSUE THREAD

**Issue by skyheat** [codersforcauses/poops#261]
**Is your feature request related to a problem? Please describe.**
Currently uses dummy data

**Describe the solution you'd like**
Link to backend

**Describe alternatives you've considered**

**Additional context**

**Comment by justinliangg** [comment]
In #262, I've changed the schema to 
```
role: string
createdAt: Timestamp
```

**Comment by Wolfgang1208** [comment]
pending #262 to be merged

**Comment by Wolfgang1208** [comment]
Adding issue score with changing firebase function: 
`
const newRole: Role = {
          role: 'Admin',
          createdAt: Timestamp.now(),
          userName: user.displayName,
          email: user.email
        }
`

**Comment by Wolfgang1208** [comment]
Having problems with query. Returning "undefined" after calling firestore api getDoc. @/hook/roles.tsx

**Comment by NicholasChoong** [comment]
this is not needed now
