### ISSUE TITLE
New User Details Phone Validation

### ISSUE THREAD

**Issue by skyheat** [codersforcauses/poops#270]
**Is your feature request related to a problem? Please describe.**
Currently, in the page where new users enter missing details, the phone number is not validated.

**Describe the solution you'd like**
Implement phone validdation.

**Describe alternatives you've considered**
Feifan: Thinking about using react hook form for validation.

**Additional context**

**Comment by scratchclaggy** [comment]
Hint: look at the phone login method where there is an example for the phone validation library already

**Comment by Wolfgang1208** [comment]
Change the direction to use react hook form
