### ISSUE TITLE
Integrate Firebase Firestore to Home, Contact and Visit page

### ISSUE THREAD

**Issue by NicholasChoong** [codersforcauses/poops#29]
## Basic Information
Schema:
Look at the page issues and design a schema with the provided details

Best practices for Firestore:
- Keep the layers as shallow as possible.
- The document names should be as random as possible to keep the locations of each document as far apart as possible to prevent hotspots
- https://firebase.google.com/docs/firestore/best-practices

## Other Information
Potential scopes:

**Comment by GlendleNguyen** [comment]
This issue has been split into separate issues 81, 82, and 83.
