### ISSUE TITLE
Update docs

### ISSUE THREAD

**Issue by NicholasChoong** [codersforcauses/poops#294]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by scratchclaggy** [comment]
We can probably remove the README content as well if it's all present in the docs. The README should probably just cover how to clone the repo, install dependencies and run dev scripts.

**Comment by NicholasChoong** [comment]
> We can probably remove the README content as well if it's all present in the docs. The README should probably just cover how to clone the repo, install dependencies and run dev scripts.

sure
