### ISSUE TITLE
Add buttons and forms for incident report and vet concerns 

### ISSUE THREAD

**Issue by NicholasChoong** [codersforcauses/poops#32]
## Basic Information
- [x] A button to pop up an incidence report form in the Visit Page
- [ ] Another one to pop up a vet concerns registration form Visit Page
- [x] Add an incidence report form in the Incident report page
- [ ] ~~Then send the completed document to POOPS via email~~

Form details:
- UserID from Firebase Auth
- User name
- Pet name
- Date and time
- vet name (for vet form)
- A textfield for the details

## Other Information
Potential scopes: Intergrate firestore to store the documents

**Comment by scratchclaggy** [comment]
@NicholasChoong How do we handle date/time with firebase? Do I want to use a Date object, pass UTC seconds, use client local time, server time, something else?

**Comment by NicholasChoong** [comment]
Use serverTimrstamp provided by firebase. This to keep the time consistent across all forms.
