### ISSUE TITLE
Construct a wireframe mockup / interface design

### ISSUE THREAD

**Issue by ivy0305** [codersforcauses/poops#34]
## Basic Information
* Construct a wireframe mockup / interface design using [Figma](https://www.figma.com)
* The goal of this task is to:
   - Visualise different pages
   - Outline the user navigation workflow (how the user navigates from one page to another)
* Pages to design:
<img width="894" alt="Screen Shot 2022-06-25 at 2 41 23 pm" src="https://user-images.githubusercontent.com/64839317/175761840-74b76002-a820-4405-a8c9-46b481ce81ae.png">
* Note that this will be a PWA, so design it as a mobile app!

**Comment by scratchclaggy** [comment]
Completed
