### ISSUE TITLE
Convert images into webp format

### ISSUE THREAD

**Issue by skyheat** [codersforcauses/poops#41]
## Basic Information
Convert all images into webp format for file size optimisation.
- [ ] Convert all images into webp format

## Other Information
Potential scopes: 
- Ignore favicons

**Comment by domcain** [comment]
Drag and drop images to here https://squoosh.app/ to convert them :)

**Comment by domcain** [comment]
Issue says "all images" (besides favicons) but I can only see 'dog-icon.png' which i have converted. I'm assuming there are plenty more to come. Should I just commit changes & submit pr, but leave this issue open while more images get added? (and whoever adds more can ping me to convert them)

**Comment by scratchclaggy** [comment]
No longer relevant
