### ISSUE TITLE
Create a user profile page

### ISSUE THREAD

**Issue by NicholasChoong** [codersforcauses/poops#43]
## Basic Information
This should display:
- [x] User name
- [x] User profile pic
- [x] User email
- [x] Selected regions
- [ ] A link that directs the user to the POOPS homepage
- [ ] a sign out button

Due to changes in the design, we will opt to have the user's profile be displayed within the contacts page. This page should remain unaffected but the link to it will no longer be in the navbar, possibly the header on the top right.

## Other Information
Potential scopes:

**Comment by pavo-etc** [comment]
A user profile page has been implemented in the contact list, currently waiting to be merged (#49).  This issue lists a few smaller details not present yet.  The contact page will need to be merged into branch [i43-create_a_user_profile_page](https://github.com/codersforcauses/poops/tree/i43-create_a_user_profile_page) before this can begin.

**Comment by scratchclaggy** [comment]
This issue was solved earlier.
