### ISSUE TITLE
Navbar indicator bugs out when page is refreshed

### ISSUE THREAD

**Issue by NicholasChoong** [codersforcauses/poops#51]
## Basic Information
Navbar indicator points back to the home icon after a page refresh regardless of what route it is at.

Description of the issue

- [x] Fix the navbar indicator by using the next route api and useEffect

## Other Information

Potential scopes:

**Comment by pavo-etc** [comment]
I have pushed a fix to the i51 branch.  It uses the `next/route` api but not `useEffect`.  It bases the initial value of currentPage on the first segment of the page URL.  Should I create a pull request for this?

**Comment by NicholasChoong** [comment]
Sure
