### ISSUE TITLE
Link Multiple Auth Providers to a Firebase Account

### ISSUE THREAD

**Issue by NicholasChoong** [codersforcauses/poops#65]
## Basic Information

Auth providers create duplicate Firebase account

- [ ] Link the auth providers

## Other Information
https://firebase.google.com/docs/auth/web/account-linking

Potential scopes:

**Comment by JakeLDev** [comment]
I think that we first need to create users in firestore, and then allow users to link their external authentication methods to their user. Might need a signup page, where they create an account, and use their external auth

Leaving this issue for now until we have the users set up in firestore

**Comment by JakeLDev** [comment]
> I think that we first need to create users in firestore, and then allow users to link their external authentication methods to their user. Might need a signup page, where they create an account, and use their external auth
> 
> Leaving this issue for now until we have the users set up in firestore

Now that I understand better about which UID we're using, I think I have all I need to get started
