### ISSUE TITLE
Adding pet names to contacts page

### ISSUE THREAD

**Issue by GlendleNguyen** [codersforcauses/poops#72]
## Basic Information
Pet names to be displayed after client names in the contacts page if pets exist. 
For example:
John Citizen - Fido

- [ ] Add client's pet names after their own name 

## Other Information

Potential scopes:

**Comment by scratchclaggy** [comment]
@GlendleNguyen thoughts on what to do when a client has multiple pets?

I'm thinking we just cap out the field to 16 chars or something? Then I guess we just maintain the order that the DB uses...

E.g. John Citizen - Fido, Spot, Luck...

**Comment by GlendleNguyen** [comment]
@scratchclaggy I think that sounds good. I don't imagine many people would have more than 3 pets so it would look fine. Also I should have added that their idea was to have the pet names be right aligned.
