### ISSUE TITLE
2-step login page for new users

### ISSUE THREAD

**Issue by NicholasChoong** [codersforcauses/poops#93]
## Basic Information

New users have to fill in their details after they have logged in.
Phone logins require new users to fill in more of their details.

Redirect new users to a form page to fill up further details.

- [x] A form for the 3rd party login providers
- [x] ~~A page for the phone login~~ A form for the new users to fill in their details after they have used their phone number to login
- [x] ~~Add the name, email and phone number of the new users to the Firebase Auth database if there are none~~

## Other Information
https://firebase.google.com/docs/reference/js/auth.userinfo

Example:
```ts
const signUp = async (auth: Auth, username: string, password: string) => {
  try {
    await createUserWithEmailAndPassword(
      auth,
      `${username}@${EMAIL_DOMAIN}`,
      password
    )
    if (auth?.currentUser?.uid) {
      await updateProfile(auth.currentUser, {
        displayName: username
      })
    }
  } catch (err: unknown) {
    if (err instanceof FirebaseError) {
      switch (err.code) {
        //#region  //*=========== For logging ===========
        default:
          console.error(err.message)
      }
    } else console.error(err)
    //#endregion  //*======== For logging ===========
  }
}
```
<img width="299" alt="Screenshot 2023-01-14 at 2 55 23 pm" src="https://user-images.githubusercontent.com/62389033/212460070-f97dcf12-173d-4e2c-8ed1-b9230873a794.png">

- only check name, email, and phone number

Potential scopes:

**Comment by Ragnaros212tt** [comment]
[loginPage.zip](https://github.com/codersforcauses/poops/files/10260468/loginPage.zip)
